version: 2

project_name: admctl

env:
  - CGO_ENABLED=0

gomod:
  proxy: true

git:
  tag_sort: -version:refname

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh

snapshot:
  version_template: "{{ incpatch .Version }}-dev"

report_sizes: true

builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.FullCommit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=Admiral

universal_binaries:
  - replace: false

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - --yes
      - --bundle=${signature}
      - ${artifact}

docker_signs:
  - cmd: cosign
    artifacts: images
    output: true
    args:
      - sign
      - --yes
      - ${artifact}@${digest}

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^test:"
      - '^chore(?!\(deps\))'
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "Features"
      regexp: '^feat(\([[:word:]]+\))?!?:.+$'
      order: 100
    - title: "Security Updates"
      regexp: '^sec(\([[:word:]]+\))?!?:.+$'
      order: 200
    - title: "Bug Fixes"
      regexp: '^fix(\([[:word:]]+\))?!?:.+$'
      order: 300
    - title: "Dependency Updates"
      regexp: '^(feat|fix)\(deps\)!?:.+$'
      order: 400
    - title: "Documentation Updates"
      regexp: '^doc(\([[:word:]]+\))?!?:.+$'
      order: 500
    - title: "Build Process Updates"
      regexp: '^build(\([[:word:]]+\))?!?:.+$'
      order: 600
    - title: "Other Changes"
      order: 9999

archives:
  - name_template: >-
      {{ .ProjectName }}-{{ .Version }}_{{ title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if and (eq .Os "darwin") (eq .Arch "all") }}universal
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats:
          - zip
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - README.md
      - LICENSE
      - completions/*

homebrew_casks:
  - name: admctl
    repository:
      owner: admiral-io
      name: homebrew-tap
    directory: Casks
    homepage: https://admiral.io/
    description: Admiral CLI - Platform Orchestrator
    binaries:
      - admctl
    completions:
      bash: completions/admctl.bash
      zsh: completions/admctl.zsh
      fish: completions/admctl.fish
    dependencies:
      - formula: git
    commit_author:
      name: admiral-ci
      email: support@admiral.io

dockers_v2:
  - images:
      - "ghcr.io/admiral-io/admctl"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "latest"
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      io.artifacthub.package.maintainers: '[{"name":"Admiral","email":"support@admiral.io"}]'
      io.artifacthub.package.license: "Apache-2.0"
      org.opencontainers.image.description: "Admiral - Platform Orchestrator CLI"
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"
    extra_files:
      - scripts/entrypoint.sh

nfpms:
  - id: admctl
    file_name_template: "{{ .ConventionalFileName }}"
    maintainer: Admiral <support@admiral.io>
    description: Admiral CLI - Platform Orchestrator
    homepage: https://admiral.io
    license: Apache-2.0
    vendor: Admiral
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/admctl.bash
        dst: /usr/share/bash-completion/completions/admctl
        file_info:
          mode: 0644
      - src: ./completions/admctl.fish
        dst: /usr/share/fish/vendor_completions.d/admctl.fish
        file_info:
          mode: 0644
      - src: ./completions/admctl.zsh
        dst: /usr/share/zsh/vendor-completions/_admctl
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/admctl/copyright
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    dependencies:
      - git
    recommends:
      - golang
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

scoops:
  - name: admctl
    repository:
      owner: admiral-io
      name: scoop-bucket
    directory: bucket
    homepage: https://admiral.io
    description: Admiral - Platform Orchestrator CLI for managing clusters, runners, and service accounts.
    license: Apache-2.0
    commit_author:
      name: admiral-ci
      email: support@admiral.io

sboms:
  - artifacts: archive

milestones:
  - close: true

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/admiral-io/admiral-cli/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## Helping out

    This release is only possible thanks to **all** the support of some **awesome people**!
